[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
ffi = true
# since we are using foundrydevOpsTools to fetch the latest contract
# we have to say ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config